version: '3.8'
services: 
    mongodb:
        image: mongo:5.0.9
        environment:
            # Credentials
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
        restart: always 
        ports:
            - 27017:27017
        extra_hosts:
            # To comunicate host with container
            - "host.docker.internal:host-gateway"
        volumes: 
            # To save data if we turn down the container
            - volume_mongo_db:/data/db 

volumes: 
    volume_mongo_db: