version: '3'
services: 
    mongodb:
        image: mongo:5.0.9
        environment:
            # Credentials
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
        restart: always 
        ports:
            - 27017:27017
        # Only for local 
        # extra_hosts:
        #     # To comunicate host with container
        #     - "host.docker.internal:host-gateway"
        volumes: 
            # To save data if we turn down the container
            - volume_mongo_db:/data/db
        # Activate logs to see them in AWS (Cloud Watch)
        logging:
            driver: awslogs
            options:
                awslogs-group: balit_logs
                awslogs-region: us-east-1
                awslogs-stream-prefix: mongodb
    shippingmicroservice:
        image: fer227/shippingmicroservice:latest
        ports:
         - 6000:6000
        # Only for local 
        # extra_hosts:
        #     # To comunicate host with container
        #     - "host.docker.internal:host-gateway"
        links:
            # To comunicate both services
            - mongodb
        # Activate logs to see them in AWS (Cloud Watch)
        logging:
            driver: awslogs
            options:
                awslogs-group: balit_logs
                awslogs-region: us-east-1
                awslogs-stream-prefix: shipping
volumes: 
    volume_mongo_db: